version: '3.8'

services:
  robo_ia_atendimento:
    container_name: appetito_robo_ia_atendimento
    build: .
    ports:
      - "8002:8002"
    env_file:
      - .env
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8002 --reload
